import { Geist, Geist_Mono } from "next/font/google";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import CartProviderWrapper from "./components/CartProviderWrapper";

import "./globals.css";
import Nav from "./components/Nav";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<SessionProviderWrapper>
					<CartProviderWrapper>
						<Nav />
						{children}
					</CartProviderWrapper>
				</SessionProviderWrapper>
			</body>
		</html>
	);
}
